version: '3.8'

services:
  # PostgreSQL 데이터베이스 서비스
  db:
    image: postgres:16-alpine
    container_name: sec-bot-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: defi!3jd1)d
      POSTGRES_DB: sec_bot_db
    ports:
      - "5432:5432" # 윈도우 PC(localhost)에서 접속하기 위해 포트 개방
    volumes:
      - /data/db:/var/lib/postgresql/data # DB 데이터를 PC에 저장 (컨테이너 삭제해도 유지됨)
